/* tslint:disable */
/* eslint-disable */
/**
 * Name Done - Auth Service
 * An authentication service API for Name Done
 *
 * The version of the OpenAPI document: 0.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailConfirmationRequiredResponseDto
 */
export interface EmailConfirmationRequiredResponseDto {
    /**
     * An informational message indicating the need for email confirmation
     * @type {string}
     * @memberof EmailConfirmationRequiredResponseDto
     */
    message: string;
}

/**
 * Check if a given object implements the EmailConfirmationRequiredResponseDto interface.
 */
export function instanceOfEmailConfirmationRequiredResponseDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function EmailConfirmationRequiredResponseDtoFromJSON(json: any): EmailConfirmationRequiredResponseDto {
    return EmailConfirmationRequiredResponseDtoFromJSONTyped(json, false);
}

export function EmailConfirmationRequiredResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailConfirmationRequiredResponseDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function EmailConfirmationRequiredResponseDtoToJSON(value?: EmailConfirmationRequiredResponseDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

